### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'dtype'

### ISSUE THREAD

**Issue by rylanchiu** [Ubiqus/OpenNMT-py#13]
I have already installed the dependecy properly. But when I run `preprocess.py` , it returns error:

```
Traceback (most recent call last):
  File "preprocess.py", line 218, in <module>
    main()
  File "preprocess.py", line 205, in main
    fields = inputters.get_fields(opt.data_type, src_nfeats, tgt_nfeats)
  File "/opt/conda/lib/python3.6/site-packages/OpenNMT_py-0.4-py3.6.egg/onmt/inputters/inputter.py", line 46, in get_fields
    return TextDataset.get_fields(n_src_features, n_tgt_features)
  File "/opt/conda/lib/python3.6/site-packages/OpenNMT_py-0.4-py3.6.egg/onmt/inputters/text_dataset.py", line 244, in get_fields
    postprocessing=make_src, sequential=False)
TypeError: __init__() got an unexpected keyword argument 'dtype'
```
But everything works find when I run the OpenNMT master on the same dataset in another docker.

**Comment by rylanchiu** [comment]
Seems that the `torchtext` version in `setup.py` should be 0.3.0

**Comment by vince62s** [comment]
Yes indeed
sudo pip install git+git://github.com/pytorch/text
