### ISSUE TITLE
How to train without gpu?

### ISSUE THREAD

**Issue by hughperkins** [Ubiqus/OpenNMT-py#7]
I get:
```
$ python train.py -data data/demo -save_model demo-model
...
Loading train dataset from data/demo.train.1.pt, number of examples: 10000
Traceback (most recent call last):
  File "train.py", line 41, in <module>
    main(opt)
  File "train.py", line 28, in main
    single_main(opt)
  File "/toknas/hugh/git/OpenNMT-Ubiqus/train_single.py", line 120, in main
    opt.valid_steps)
  File "/toknas/hugh/git/OpenNMT-Ubiqus/onmt/trainer.py", line 142, in train
    if (i % self.n_gpu == self.gpu_rank):
ZeroDivisionError: integer division or modulo by zero
```

**Comment by vince62s** [comment]
We did not intend to support training without GPU but I just pushed a fix
thanks to @se4u

**Comment by hughperkins** [comment]
Thanks!
